### ISSUE TITLE
Can't run SINE. java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by UralZima** [adolfintel/sine#1]
Hello. I just discovered your project. It is AWESOME. I used Gnaural before, it is not very user-friendly. But I still didn't tried your app, only saw screenshots and web version. I can't run it :(

I downloaded your binary package and tried to run it on Gentoo. 

user@localhost ~/tmp/sine $ java -jar SINE-Editor.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: com/dosse/bwentrain/core/Preset
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethod(Class.java:2128)
        at java.awt.Component.isCoalesceEventsOverriden(Component.java:6218)
        at java.awt.Component.access$500(Component.java:186)
        at java.awt.Component$3.run(Component.java:6172)
        at java.awt.Component$3.run(Component.java:6170)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Component.checkCoalescing(Component.java:6169)
        at java.awt.Component.<init>(Component.java:6138)
        at java.awt.Container.<init>(Container.java:283)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:188)
        at com.dosse.bwentrain.editor.Main.<init>(Main.java:227)
        at com.dosse.bwentrain.editor.Main.main(Main.java:1157)
Caused by: java.lang.ClassNotFoundException: com.dosse.bwentrain.core.Preset
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 17 more

user@localhost ~/tmp/sine $ java -jar SINE.jar       
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/axet/apple/Apple$OpenFilesHandler
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.github.axet.apple.Apple$OpenFilesHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

user@localhost ~/tmp/sine $ java -version            
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (Gentoo icedtea-3.3.0)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

Please help

**Comment by adolfintel** [comment]
Hi, that happens if it can't access the jar files in the lib folder. Make sure the permissions are at least 755 on those files

**Comment by UralZima** [comment]
Thanks for answer. I checked the lib folder and it was empty.
The problem was because I extracted the archive using '7z e' instead of '7z x'. 
Thanks it works!
P.S. Your site is very slow, I am using it 3 days and 20-30% connection attempts fails

**Comment by adolfintel** [comment]
I know, I have contacted my hosting provider about this issue
